<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Clinica</title>
</head>

<body>
    <!-- main header -->
    <header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand">CLINICA - TURNOS</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <?php if ($this->user): ?>
                        <!-- Mostrar links si el usuario está logueado -->
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/tp-2-web/listar">Turnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/tp-2-web/clientes">Clientes</a>
                        </li>
                    <?php else: ?>
                        <!-- Mostrar links para no logueado -->
                        <li class="nav-item">
                            <a class="nav-link" href="/tp-2-web/homeTurno">Turnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/tp-2-web/homeCliente">Clientes</a>
                        </li>
                    <?php endif; ?>
                </ul>

                <!-- Botones de sesión alineados a la derecha -->
                <ul class="navbar-nav ms-auto">
                    <?php if ($this->user): ?>
                        <li class="nav-item">
                            <a class="nav-link session" href="/tp-2-web/logout">Salir</a>
                        </li>
                    <?php else: ?>
                        <li class="nav-item">
                            <a class="nav-link session" href="/tp-2-web/showLogin">Iniciar sesión</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
</header>


    <main class="container mt-3">