<?php require 'templates/layout/header.phtml'; ?>


<h1>Editar Turno</h1>

<!-- Mostrar los datos del cliente -->
<form method="POST" action="editarTurno">
    <div class="form-group">
        <label for="nombre">ID:</label>
        <input type="text" id="id_turno" name="id_turno" value="<?= $turno->id_turno ?>" readonly class="form-control" />
    </div>
    <div class="form-group">
        <label for="fecha_turno">Fecha de Turno:</label>
        <input type="date" id="fecha_turno" name="fecha_turno" class="form-control" />
    </div>

    <div class="form-group">
        <label for="hora_turno">Hora de Turno:</label>
        <input type="time" id="hora_turno" name="hora_turno" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

<?php require 'templates/layout/footer.phtml'; ?>