<?php require 'templates/layout/header.phtml'; ?>


<h1>Editar Cliente</h1>

<!-- Mostrar los datos del cliente -->
<form method="POST" action="editarCliente"> 
<div class="form-group">
        <label for="nombre">ID:</label>
        <input type="text" id="id_cliente" name="id_cliente" value="<?= $cliente->id_cliente ?>" readonly class="form-control" />
        </div>
    <div class="form-group">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="<?= $cliente->nombre ?>" class="form-control" />
    </div>
    <div class="form-group">
        <label for="telefono">Teléfono:</label>
        <input type="text" id="telefono" name="telefono" value="<?= $cliente->telefono ?>" class="form-control" />
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" value="<?= $cliente->email ?>" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

<?php require 'templates/layout/footer.phtml'; ?>