<?php require 'templates/layout/header.phtml'; ?>


<ul class="list-group">
    <h1 class="text-center">Listado de Turnos</h1>
    <?php foreach ($turnos as $turno): ?>
        <li class="list-group-item item-task <?php if ($turno->finalizado): ?> finished <?php endif ?>">
            <div class="label">
                <!-- Mostrar la foto del cliente si existe -->
                <?php if (!empty($turno->foto_cliente)): ?>
                    <img src="<?= $turno->foto_cliente ?>" alt="Foto de <?= $turno->nombre_cliente ?>" class="rounded-circle" style="width: 50px; height: 50px; margin-right: 10px;">
                <?php endif; ?>

                <b> <?= $turno->nombre_cliente ?> </b>
                <b>Fecha:</b> <?= $turno->fecha_turno ?> 
                

            </div>
            
            <!-- Sección para mostrar detalles, inicialmente oculta -->
            
            
            <div class="actions">
            

<?php if (!$turno->finalizado): ?>
    <a href="completar/<?= $turno->id_turno ?>" type="button" class='btn btn-success btn-sm ml-auto cancelar-btn'>Cancelar</a>
<?php endif ?>
<a href="eliminar/<?= $turno->id_turno ?>" type="button" class='btn btn-danger btn-sm ml-auto borrar-btn'>Borrar</a>
<a href="editarT/<?= $turno->id_turno ?>" type="button" class='btn btn-danger btn-sm ml-auto editar-btn'>Editar</a>
</div>
                    <a href="detalles/<?= $turno->id_turno ?>" type="button" class='btn btn-info btn-sm ml-auto detalles-btn'>Detalles</a>
                    
                </div>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<a href="formulario" type="button" class="btn btn-primary btn-block">Agregar Turno</a>

<p class="mt-3"><small>Mostrando <?= count($turnos) ?> turnos</small></p>

<?php require 'templates/layout/footer.phtml'; ?>
